DROP TABLE VOTACAO;

DROP TABLE PAUTA;

CREATE TABLE PAUTA (
    ID_PAUTA VARCHAR(20) AUTO_INCREMENT PRIMARY KEY NOT NULL,  
    TEMPO NUMBER(5),
    DATA_SESSAO TIMESTAMP NOT NULL  
);

CREATE TABLE VOTACAO (    
    CPF VARCHAR(11) PRIMARY KEY NOT NULL,
    VOTO VARCHAR(2) NOT NULL,
    ID_PAUTA VARCHAR(20) NOT NULL,
    CONSTRAINT FK_pauta FOREIGN KEY (ID_PAUTA)
    REFERENCES PAUTA(ID_PAUTA)    
);
